name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.3.0
      with:
        version: v24.0.9
    
    - name: Build the Docker image
      run: docker build -t thejitenderk/backend:v3 .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      continue-on-error: true
      with:
        image-ref: 'thejitenderk/backend:v3'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan report
      uses: actions/upload-artifact@v4.6.2
      with:
        name: trivy-results
        path: trivy-results.sarif

