name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.3.0
      with:
        version: v24.0.9
    
    - name: Build the Docker image
      run: docker build -t thejitenderk/backend:v2 .

    - name: Docker Scout
      id: docker-scout
      if: ${{ github.event_name == 'pull_request' }}
      uses: docker/scout-action@v1
      with:
        image: thejitenderk/backend:v2
        only-severities: critical,high
    
    - uses: docker/login-action@v3.5.0
      with:
        username: thejitenderk
        password: Iwant2learn    

        
    - name: Docker Push
      run: docker push thejitenderk/backend:v2
