name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.3.0
      with:
        version: v24.0.9
      
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag backend:$(date +%s)
      
    # - uses: docker/login-action@v3.5.0
    #   with:
    #     username: thejitenderk
    #     password: Iwant2learn
        
    # - name: Docker Push
    #   run: docker tag backend:$(date +%s) thejitenderk/backend:$(date +%s)
