name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.3.0
      with:
        version: v24.0.9
    
    - uses: docker/login-action@v3.5.0
      with:
        username: thejitenderk
        password: Iwant2learn
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag backend:v1
      

        
    - name: Docker Push
      run: docker tag backend:v1 thejitenderk/backend:v1
